language: java
jdk: openjdk6
script: mvn -B clean package
env:
  global:
  - GH_PROJECT_NAME: Mathematica-IntelliJ-Plugin
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - secure: EtVpVE54lkCGHxShrBXspb1dNZ0kgBgaiziWNLUlgt1dZx9yVrj4/dcc+OxHpjIoI/lxR/tNwZ5byPJCgYUdS8skjdPuqgf13dTh0Mi72M3xSF6q1D/K12YT5KT8qgJNqKxjm4fsIPcktFWPJAcZFRvKcEeeiSBdrnDgdrLIhSs=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hTdCeGKOWi/Frbo3v9mUBvu+9NMIcD9rQrpQHQVC6WfRFGk329XDwnbQ6tscaY8qS9Mw+CQuxF/M0kgjNT4Ib0pVYee8+pCcDCnqOZBEOiADSo+kSERKKCxMII/9u4o+w7mtuEADBo6u6SlxBTHM6+mpv+MTCX4lEhvuWAcVXlI=
  file: Mathematica-IntelliJ-Plugin-bin.zip
  on:
    repo: halirutan/Mathematica-IntelliJ-Plugin
    tags: true
    all_branches: true
