language: java
jdk: openjdk6
script: mvn clean package
env:
  global:
  - GH_PROJECT_NAME: Mathematica-IntelliJ-Plugin
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - secure: EtVpVE54lkCGHxShrBXspb1dNZ0kgBgaiziWNLUlgt1dZx9yVrj4/dcc+OxHpjIoI/lxR/tNwZ5byPJCgYUdS8skjdPuqgf13dTh0Mi72M3xSF6q1D/K12YT5KT8qgJNqKxjm4fsIPcktFWPJAcZFRvKcEeeiSBdrnDgdrLIhSs=